@startuml
skinparam RoundCorner 0
hide empty fields
hide empty methods
skinparam ClassAttributeIconSize 0
skinparam Shadowing true
skinparam BackgroundColor transparent
interface "DeliveriesNavigatorParams" {
    +ProductItem : { item: Delivery }
    +ProductsList : undefined
}
class "ParamListBase"
hide "ParamListBase" circle
"ParamListBase" <|-- "DeliveriesNavigatorParams"
@enduml