@startuml
skinparam RoundCorner 0
hide empty fields
hide empty methods
skinparam ClassAttributeIconSize 0
skinparam Shadowing true
skinparam BackgroundColor transparent
interface "LoadingIndicatorContainerStyleType" {
    +backgroundColor : ColorValue
}
class "ViewStyle"
hide "ViewStyle" circle
"ViewStyle" <|-- "LoadingIndicatorContainerStyleType"
@enduml