@startuml
skinparam RoundCorner 0
hide empty fields
hide empty methods
skinparam ClassAttributeIconSize 0
skinparam Shadowing true
skinparam BackgroundColor transparent
interface "LoadingIndicatorTextType" {
    +color : string
    +fontWeight : "100" | "200" | "400" | "600" | 200 | 100 | "normal" | "bold" | "300" | "500" | "700" | "800" | "900" | 300 | 400 | 500 | 600 | 700 | 800 | 900 | "ultralight" | "thin" | "light" | "medium" | "regular" | "semibold" | "condensedBold" | "condensed" | "heavy" | "black"
}
class "TextStyle"
hide "TextStyle" circle
"TextStyle" <|-- "LoadingIndicatorTextType"
@enduml