@startuml
skinparam RoundCorner 0
hide empty fields
hide empty methods
skinparam ClassAttributeIconSize 0
skinparam Shadowing true
skinparam BackgroundColor transparent
interface "RouteParams" {
    +params : { item?: undefined; reload?: boolean }
}
class "ParamListBase"
hide "ParamListBase" circle
"ParamListBase" <|-- "RouteParams"
@enduml